In [6]:
# load pandas
import pandas as pd
# load numpy
import numpy as np

# data location
url='../data/InputParameters.txt'

# load data
dataframe=pd.read_csv(url,header=None,sep='\s+ ',engine='python')

# dataframe.head(2)
# dataframe[0].head(2)

n=dataframe.shape[0]
n

src=0
data=np.array(dataframe[src])
#v

def moment(mm, data):
    """computes mm-th raw moment"""
    return np.mean(data**mm)
    
def Hankel(mmx,data):
    """generates Hankel matrix"""
    H=np.zeros((mmx+1,mmx+1))
    for i in range(mmx+1):
        for j in range(i,mmx+1):
            H[i,j]=moment(i+j,data)
            H[j,i]=H[i,j]
    return H

def aPCcfs(H,k=-1,len=-1):
    """polynomial coefficients in increasing order, Sergey style"""
    l=H.shape[0]
    if len==-1:
        len=l
    elif len>l:
        return -1
    cfs=np.zeros(len)
    if k<0:
        k=l-1
    elif k==0:
        cfs[0]=1
        return cfs
    elif k>=l:
        return -1
    rH=H[0:k+1,0:k+1]
    rs=np.zeros(k+1)
    rs[-1]=1
    for j in range(k+1):
        rH[k,j]=0
    rH[k,k]=1
    cfs=np.linalg.solve(rH,rs)
    cfs.resize(len)
    return cfs
 
def PCcfs(H,k=-1,len=-1):
    """polynomial coefficientes in increasing order, Gautschi style via moment determinants (p. 53)"""
    l=H.shape[0]
    if len==-1:
        len=l
    elif len>l:
        return -1
    cfs=np.zeros(len)
    if k<0:
        k=l-1
    elif k==0:
        cfs[0]=1
        return cfs
    elif k>=l:
        return -1
    rH=H[0:k,0:k]
    idx=np.ones(l,dtype=bool)
    idx[k+1:l]=False
    delta=np.linalg.det(rH)
    for i in range(0,k):
        idx[i]=False
        Hk=H[0:k,idx]
        dHk=np.linalg.det(Hk)
        cfs[i]=(-1)**(k+i) * dHk/delta
        idx[i]=True
    cfs[k]=1
    return cfs

def cmpAlphaBeta(H,k=-1):
    """generates vectors of recursion coefficientes alpha and beta"""
    n=H.shape[0]
    if k==-1:
        k=n-1
    elif k>=n:
        return -1
    alpha=np.zeros(k)
    beta=np.zeros(k)
    delta=np.zeros(k+1)
    deltak=np.zeros(k+1)
    idx=np.zeros(n,dtype=bool)
    for l in range(1,k+1):
        print(l)
        delta[l]=np.linalg.det(H[0:l-1,0:l-1])
        if l>1:
            idx[0:l-2]=True
            idx[l]=True
            deltak[l]=np.linalg.det(H[0:l-1,idx])
            idx[0:n]=False
    delta[0]=1
    deltak[0]=0
    deltak[1]=H[0,1]
    for l in range(k):
        alpha[l]=deltak[l+1]/delta[l+1] - deltak[l]/delta[l]
        beta[l]=delta[l+1]*delta[l-1]/delta[l]**2
    return alpha, beta
    
#H
mm=5
#out=moment(mm,v)
#out
k=4
H=Hankel(mm,data)   
print(H)
#print(np.linalg.det(H))
acfs=aPCcfs(H,k)
print(acfs)
cfs=PCcfs(H,k)
print(cfs)
#np.linalg.cond(H)
alpha, beta=cmpAlphaBeta(H)
print(alpha)
print(beta)

[[ 1.          0.66786794  0.47839582  0.35983777  0.2806236   0.22502949]
 [ 0.66786794  0.47839582  0.35983777  0.2806236   0.22502949  0.18448914]
 [ 0.47839582  0.35983777  0.2806236   0.22502949  0.18448914  0.15400466]
 [ 0.35983777  0.2806236   0.22502949  0.18448914  0.15400466  0.13049751]
 [ 0.2806236   0.22502949  0.18448914  0.15400466  0.13049751  0.1119858 ]
 [ 0.22502949  0.18448914  0.15400466  0.13049751  0.1119858   0.097146  ]]
[ 0.06702425 -0.61732735  1.87851834 -2.31779459  1.          0.        ]
[ 0.06702425 -0.61732735  1.87851834 -2.31779459  1.          0.        ]
1


LinAlgError: Arrays cannot be empty

In [24]:
import numpy as np

a=np.array([1,0,3])
c=np.flip(a,0)
np.polyval(c,5)
p=np.poly1d(c)
p(5)
p.c # show the coefficients
q=p**2 # square the polynomial p
q.c
q(5)
print(p)
p.r # roots
l=3
k=4
ar=np.arange(k)
A=np.array([ar, ar])
idx=np.ones(k,dtype=bool)
idx[[l]]=False
ar[idx]
A[0:2,idx]

   2
3 x + 1


array([[0, 1, 2],
       [0, 1, 2]])