In [1]:
# load pandas
import pandas as pd
# load numpy
import numpy as np
import math
import polytools as pt
import wavetools as wt

# data location
url='../data/InputParameters.txt'

# load data
dataframe=pd.read_csv(url,header=None,sep='\s+ ',engine='python')
print('df shape',dataframe.shape)
src=0
Nr=1
Nri=0
print('Nr=',Nr,' Nri=',Nri)
lb,rb=pt.cmpLRB(Nr,Nri)
dlb=dataframe[src].quantile(lb)
drb=dataframe[src].quantile(rb)
print(lb,rb,dlb,drb)
ad=dataframe[(dataframe[src]>=dlb) & (dataframe[src]<=drb)]
adata=dataframe[src]
b=pt.cmpQuantDomain(adata,dlb,drb)
#print(ad[src].describe(),'\n',adata[b].describe())
qlb=dataframe.quantile(lb)
qrb=dataframe.quantile(rb)
qb=pt.cmpQuantDomain(dataframe,qlb,qrb)
#dataframe[qb].describe()

df shape (10000, 4)
Nr= 1  Nri= 0
0.0 0.5 0.047132827999999995 0.68828345


In [16]:
nNri=2**Nr
No=4
nsrc=4
for Nri in range(nNri):
    lb,rb=pt.cmpLRB(Nr,Nri)
    qlb=dataframe.quantile(lb)
    qrb=dataframe.quantile(rb)
    #print(lb,rb,qlb,qrb)
    bd=pt.cmpQuantDomain(dataframe,qlb,qrb)
    qdata=dataframe[bd]
    #print(qdata.describe())
    for src in range(nsrc):
        cf=np.zeros([No+1,No+1])
        ncf=np.zeros([No+1,No+1])
        H=pt.Hankel(No,qdata[src])
        r,w=pt.cmpGrw(H)
        print('H=',H)
        for k in range(No+1):
            cf[k,:]=pt.aPCcfs(H,k)
            #c=np.flip(cv[k,:],0)
            #p=np.poly1d(c)
            #r=p.r
            #w=pt.genGW(H[0,:],r)
            nc=pt.cmpNormCf(cf[k,:],r,w)
            ncf[k,:]=cf[k,:]/nc

        print('(',src,',',Nri,'):\n',cf,'\n',ncf,'\n')

H= [[ 1.          0.52103937  0.28711388  0.16428923  0.09658784]
 [ 0.52103937  0.28711388  0.16428923  0.09658784  0.05795279]
 [ 0.28711388  0.16428923  0.09658784  0.05795279  0.03532659]
 [ 0.16428923  0.09658784  0.05795279  0.03532659  0.02180839]
 [ 0.09658784  0.05795279  0.03532659  0.02180839  0.01360296]]
( 0 , 0 ):
 [[ 1.          0.          0.          0.          0.        ]
 [-0.52103937  1.          0.          0.          0.        ]
 [-0.20151272 -0.16428923  1.          0.          0.        ]
 [-0.10228494 -0.08706682 -0.05795279  1.          0.        ]
 [-0.05704272 -0.05025023 -0.03406274 -0.02180839  1.        ]] 
 [[  1.           0.           0.           0.           0.        ]
 [ -4.16740158   7.99824699   0.           0.           0.        ]
 [ -2.04100414  -1.66398925  10.12841351   0.           0.        ]
 [ -1.38084687  -1.17540222  -0.78236281  13.50000192   0.        ]
 [ -1.0627816   -0.93622836  -0.63463393  -0.40631932  18.6313263 ]] 

H= [[  1