In [2]:
# load pandas
import pandas as pd
# load numpy
import numpy as np
import math
# own 
import aMRPC.polytools as pt
import aMRPC.wavetools as wt
import aMRPC.datatools as dt

# data location
url='../data/InputParameters.txt'

# load data
dataframe=pd.read_csv(url,header=None,sep='\s+ ',engine='python')
print('df shape',dataframe.shape)
src=0
Nr=1
Nri=0
print('Nr=',Nr,' Nri=',Nri)
lb,rb=dt.cmpLRB(Nr,Nri)
dlb=dataframe[src].quantile(lb)
drb=dataframe[src].quantile(rb)
print(lb,rb,dlb,drb)
ad=dataframe[(dataframe[src]>=dlb) & (dataframe[src]<=drb)]
adata=dataframe[src]
b=dt.cmpQuantDomain(adata,dlb,drb)
#print(ad[src].describe(),'\n',adata[b].describe())
qlb=dataframe.quantile(lb)
qrb=dataframe.quantile(rb)
qb=dt.cmpQuantDomain(dataframe,qlb,qrb)
#dataframe[qb].describe()

df shape (10000, 4)
Nr= 1  Nri= 0
0.0 0.5 0.047132827999999995 0.68828345


In [3]:
nNri=2**Nr
No=4
nsrc=4
for Nri in range(nNri):
    lb,rb=dt.cmpLRB(Nr,Nri)
    qlb=dataframe.quantile(lb)
    qrb=dataframe.quantile(rb)
    #print(lb,rb,qlb,qrb)
    bd=dt.cmpQuantDomain(dataframe,qlb,qrb)
    qdata=dataframe[bd]
    #print(qdata.describe())
    for src in range(nsrc):
        cf=np.zeros([No+1,No+1])
        ncf=np.zeros([No+1,No+1])
        H=pt.Hankel(No,qdata[src])
        r,w=pt.cmpGrw(H)
        print('H=',H)
        for k in range(No+1):
            cf[k,:]=pt.aPCcfs(H,k)
            #c=np.flip(cv[k,:],0)
            #p=np.poly1d(c)
            #r=p.r
            #w=pt.genGW(H[0,:],r)
            nc=pt.cmpNormCf(cf[k,:],r,w)
            ncf[k,:]=cf[k,:]/nc

        print('(',src,',',Nri,'):\n',cf,'\n',ncf,'\n')

H= [[ 1.          0.52103937  0.28711388  0.16428923  0.09658784]
 [ 0.52103937  0.28711388  0.16428923  0.09658784  0.05795279]
 [ 0.28711388  0.16428923  0.09658784  0.05795279  0.03532659]
 [ 0.16428923  0.09658784  0.05795279  0.03532659  0.02180839]
 [ 0.09658784  0.05795279  0.03532659  0.02180839  0.01360296]]
( 0 , 0 ):
 [[ 1.          0.          0.          0.          0.        ]
 [-0.52103937  1.          0.          0.          0.        ]
 [ 0.20258506 -0.93985015  1.          0.          0.        ]
 [-0.06613947  0.54075506 -1.32318384  1.          0.        ]
 [ 0.01928561 -0.24197005  1.0039266  -1.69237376  1.        ]] 
 [[  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [ -4.16740158e+00   7.99824699e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  1.08979544e+01  -5.05587348e+01   5.37944637e+01   0.00000000e+00
    0.00000000e+00]
 [ -2.23532764e+01   1.82759978e+02  -4.47198865e+02   3.37971832e+02
    0.00000