In [1]:
# test for wavelets details

# load pandas
import pandas as pd
# load numpy
import numpy as np
#import math
import matplotlib.pyplot as plt
import polytools as pt
import wavetools as wt

# data location
url='../data/InputParameters.txt'

# load data
dataframe=pd.read_csv(url,header=None,sep='\s+ ',engine='python')

No=4
src=0
epsilon=.1

data=dataframe[src]
#q=data.quantile(0.5)
#b=data>=q
#data=data[b]
wv=wt.wavetools(No)
wv.genWVlets()
r=wv.roots
len=r.shape[0]
QuantileOnRoots=np.zeros(len)

for i in range(len):
    QuantileOnRoots[i]=data.quantile(r[i])
    
print(QuantileOnRoots)
details=wv.cmpDetails(QuantileOnRoots)
print(details)

[  6.93889390e-17  -2.45422439e-01  -2.45422439e-01  -2.15329895e-01] [[  0.69549257   0.           0.           0.        ]
 [  6.37943556   0.           0.           0.        ]
 [-23.31126207   0.           0.           0.        ]
 [ 15.54084138   0.           0.           0.        ]]
[-0.24542244 -0.24542244 -0.21532989 -0.18523735] [[  0.69549257  -0.22201202   0.           0.        ]
 [  6.37943556   5.13573296   0.           0.        ]
 [-23.31126207 -13.60164622   0.           0.        ]
 [ 15.54084138   7.77042069   0.           0.        ]]
[-0.24542244 -0.21532989 -0.18523735 -0.16006032] [[  0.69549257  -0.22201202  -0.13569089   0.        ]
 [  6.37943556   5.13573296   2.29432673   0.        ]
 [-23.31126207 -13.60164622  -5.5953543    0.        ]
 [ 15.54084138   7.77042069   2.43289275   0.        ]]
[-0.21532989 -0.18523735 -0.16006032 -0.1397988 ] [[  0.69549257  -0.22201202  -0.13569089  -0.05944049]
 [  6.37943556   5.13573296   2.29432673   0.85563987]
 [-23.3